
dtb-$(CONFIG_MSM_GVM_QUIN) += vplatform-lfv-msm8996.dtb

dtb-$(CONFIG_ARCH_MSMCOBALT) += msmcobalt-sim.dtb \
	msmcobalt-rumi.dtb \
	msmcobalt-cdp.dtb \
	msmcobalt-mtp.dtb \
	msmcobalt-v2-sim.dtb \
	msmcobalt-v2-rumi.dtb \
	msmcobalt-v2-mtp.dtb \
	msmcobalt-v2-cdp.dtb

dtb-$(CONFIG_ARCH_MSM8937) += msm8937-rumi.dtb \
	msm8937-pmi8950-cdp.dtb \
	msm8937-pmi8937-cdp.dtb \
	msm8937-pmi8940-cdp.dtb \
	msm8937-pmi8950-ext-codec-cdp.dtb \
	msm8937-pmi8950-mtp.dtb \
	msm8937-pmi8937-mtp.dtb \
	msm8937-pmi8940-mtp.dtb \
	msm8937-pmi8950-rcm.dtb \
	msm8937-pmi8937-rcm.dtb \
	msm8937-pmi8940-rcm.dtb \
	msm8937-pmi8950-qrd-sku1.dtb \
	msm8937-pmi8937-qrd-sku2.dtb \
	msm8937-pmi8950-qrd-sku1-dvt1.dtb \
	msm8937-pmi8937-qrd-sku2-dvt1.dtb \
	apq8037-pmi8950-cdp.dtb \
	apq8037-pmi8937-cdp.dtb \
	apq8037-pmi8950-mtp.dtb \
	apq8037-pmi8937-mtp.dtb

dtb-$(CONFIG_ARCH_MSM8917) += msm8917-rumi.dtb \
	apq8017-pmi8937-cdp.dtb \
	apq8017-pmi8937-mtp.dtb \
	apq8017-pmi8950-cdp.dtb \
	apq8017-pmi8950-mtp.dtb \
	msm8917-pmi8937-cdp.dtb \
	msm8917-pmi8937-mtp.dtb \
	msm8917-pmi8940-cdp.dtb \
	msm8917-pmi8940-mtp.dtb \
	msm8917-pmi8950-cdp.dtb \
	msm8917-pmi8950-cdp-mirror-lake-touch.dtb \
	msm8917-pmi8950-ext-codec-cdp.dtb \
	msm8917-pmi8950-mtp.dtb \
	msm8917-pmi8937-rcm.dtb \
	msm8917-pmi8940-rcm.dtb \
	msm8917-pmi8950-rcm.dtb \
	msm8917-qgp-tmo.dtb \
	msm8917-pmi8937-qrd-sku5.dtb \
	apq8017-pmi8937-cdp-wcd-rome.dtb \
	apq8017-pmi8950-cdp-wcd-rome.dtb \
	apq8017-no-pmi-wcd-rome-cdp.dtb


dtb-$(CONFIG_ARCH_MSM8953) += msm8953-qrd-sku3-e7.dtb

#<<<<<<<HEAD
#dtb-$(CONFIG_ARCH_SDM450) += sdm450-rcm.dtb \#
#	sdm450-cdp.dtb #\#
#	sdm450-mtp.dtb #\#
#	sdm450-qrd.dtb #\
#	sdm450-pmi8940-mtp.dtb \
##	sdm450-pmi8937-mtp.dtb \
#	sdm450-iot-mtp.dtb \
#	sda450-cdp.dtb \
#	sda450-mtp.dtb
#
#-$(CONFIG_ARCH_MDM9607) += mdm9607-rumi.dtb \
#	mdm9607-cdp.dtb \
#	mdm9607-mtp.dtb \
#	mdm9607-rcm.dtb \
#	mdm9607-mtp-sdcard.dtb \
#	mdm9607-ttp.dtb \
#	mdm9206-mtp.dtb \
#	mdm9206-cdp.dtb \
#	mdm9206-mtp-sdcard.dtb \
#	mdm9206-rcm.dtb
#
#tb-$(CONFIG_ARCH_MSM8916) += msm8952-qrd-skum.dtb \
  #     msm8952-cdp.dtb \
   #    msm8952-ext-codec-cdp.dtb \
 #      msm8952-mtp.dtb

#dtb-$(CONFIG_ARCH_MSM8909) += msm8909-pm8916-mtp.dtb \
#	msm8909-cdp.dtb \
 #       msm8909-1gb-qrd-skuc.dtb \
  #      msm8909-1gb-qrd-skue.dtb \
   #     msm8909-qrd-skue.dtb \
#	msm8909w-wtp.dtb \
#	apq8009w-wtp.dtb \
##	apq8009w-cdp.dtb \
#	msm8909w-swoctp.dtb \
#	msm8909w-swoctp-circpanel.dtb \
#	apq8009w-swoctp.dtb \
##	apq8009w-swoctp-circpanel.dtb \
#	apq8009w-nowgr-swoctp.dtb \
#	apq8009w-nowgr-swoctp-circpanel.dtb \
#	msm8909-pm8916-cdp.dtb \
#	msm8909w-cdp.dtb \
#	msm8909w-1gb-wtp.dtb \
#	apq8009w-1gb-wtp.dtb \
#	msm8909w-1gb-cdp.dtb \
#	apq8009w-1gb-cdp.dtb \
#	msm8909w-1gb-swoctp.dtb \
#	msm8909w-1gb-swoctp-circpanel.dtb \
#	apq8009w-1gb-swoctp.dtb \
#	apq8009w-1gb-swoctp-circpanel.dtb \
#	apq8009w-1gb-nowgr-swoctp.dtb \
#	apq8009w-1gb-nowgr-swoctp-circpanel.dtb \
#	msm8909w-bg-wtp-v1.dtb \
#	msm8909w-bg-wtp-v2.dtb \
#	apq8009w-bg-wtp-v1.dtb \
#	apq8009w-bg-wtp-v2.dtb \
#	apq8009-mtp-wcd9326.dtb \
#	msm8909-mtp-wcd9326.dtb \
#	msm8909-mtp-wcd9326-refboard.dtb \
#	msm8909-512mb-mtp-wcd9326-refboard.dtb \
#	msm8909-512mb-cdp-wcd9326-refboard.dtb \
#	msm8909-512mb-rcm-wcd9326-refboard.dtb \
#	msm8909-cdp-wcd9326-refboard.dtb \
#	msm8909-rcm-wcd9326-refboard.dtb \
#	apq8009-mtp-wcd9326-refboard.dtb \
#	apq8009-512mb-mtp-wcd9326-refboard.dtb \
#	apq8009-512mb-cdp-wcd9326-refboard.dtb \
#	apq8009-512mb-rcm-wcd9326-refboard.dtb \
#	apq8009-cdp-wcd9326-refboard.dtb \
##	apq8009-rcm-wcd9326-refboard.dtb \
#	apq8009-robot-refboard.dtb \
#	apq8009-robot-rome.dtb \
##	apq8009-mtp-drone.dtb \
#	msm8909-mtp.dtb \
##	msm8909-1gb-mtp.dtb \
#	msm8909-1gb-rcm.dtb \
#	msm8909-pm8916-1gb-rcm.dtb \
##	msm8909-1gb-cdp.dtb \
#	apq8009-dragon.dtb
#=======
#©>>>>>> a87054ac0542... Kernel: Xiaomi kernel changes for MI A2 Lite Android P

ifeq ($(CONFIG_ARM64),y)
always          := $(dtb-y)
subdir-y        := $(dts-dirs)
else
targets += dtbs
targets += $(addprefix ../, $(dtb-y))

$(obj)/../%.dtb: $(src)/%.dts FORCE
        $(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/,$(dtb-y))
endif
clean-files := *.dtb
